<a href="https://colab.research.google.com/github/abcsilence/BuildingBlocks/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


In [3]:
np

<module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'>

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [11]:
a = np.array([1, 2, 3, 5, 7, 12])
a

array([ 1,  2,  3,  5,  7, 12])

In [12]:
a[2] = 10

In [13]:
a

array([ 1,  2, 10,  5,  7, 12])

In [16]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [17]:
np.linspace(0, 100, 11) #creates array with evenly spaced numbers within a spec

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

Multidimensional arrays

In [18]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [20]:
n = np.array([
    [1,2, 3],
    [4, 5, 6],
    [7, 8, 9]])

In [21]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
n[0,1] = 20

In [23]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [24]:
n[2]=[1,1,1]

In [25]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [27]:
n[:, 2]=[0,1,2]

In [28]:
n


array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

Random Generated arrays

In [29]:
np.random.rand(3)

array([0.84889935, 0.54045384, 0.48930247])

In [30]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [31]:
np.random.rand(3)*(100)

array([62.11338328, 52.91420943, 13.45799453])

Element wise operation

In [34]:
a = np.arange(5)
a


array([0, 1, 2, 3, 4])

In [35]:
b =(10+(a*2))

In [36]:
b

array([10, 12, 14, 16, 18])

Comparision Operator

In [37]:
a

array([0, 1, 2, 3, 4])

In [38]:
a>=2

array([False, False,  True,  True,  True])

In [39]:
b

array([10, 12, 14, 16, 18])

In [40]:
a>b

array([False, False, False, False, False])

Summarize

In [41]:
a.std()

1.4142135623730951

In [42]:
a.min()

0

In [43]:
a.max()

4

In [44]:
a.sum()

10